# name: Backend Push to Main

# on:
#   push:
#     branches:
#       - '*'
#       - '!main'

# jobs:
#   push-to-main:
#     runs-on: 
#             - ubuntu-latest
#             - windows-latest
#             - macos-latest

#     steps:
#       - name: Checkout main branch
#         uses: actions/checkout@v2
#         with:
#           ref: main

#       - name: Merge changes from push event branch
#         run: |
#           git checkout -b temp-branch
#           git fetch origin ${{ github.event.ref }}
#           git merge --no-ff --no-edit origin/${{ github.event.ref }}
#           git push origin temp-branch:main

#       - name: Cleanup
#         run: |
#           git checkout main
#           git branch -D temp-branch
